# App_Page : Login
username = "name:j_username"
password = "name:j_password"
btn_ok = "name:Submit"
btn_suok = "name:SuOkButton"
btn_close = "name:JSP_CLOSE_BUTTON"

# App_Page : Logout
link_logout = "link:Logout"
btn_yes = "name:YesButton"
msg_logout = "//div[@class='InfoTxt']"

# App_Page : Solution unit links
link_customers = "link:Customers"
link_create_customer = "link:Rapid activation: Create customer"
link_search_customer = "link:Search for customer"

link_large_accounts = "link:Large accounts"
link_searchlevel = "link:Search for level or subscriber"
link_create_large_account = "link:Create large account"
link_create_top_level = "link:Create top level"
link_create_level_or_sub = "link:Create level or subscriber"

link_contracts = "link:Contracts"
link_create_contract = "link:Rapid activation: Create contract"
link_searchcontract = "link:Search for contract"
contract_table_search = "class:DABgForm"
link_contract_overview = "link:Contract overview"
rateplan_template = "name:CONTRACT_TEMPLATE"
btn_rp_template_filter = "name:FILTER_BUTTON"
sim = "name:STOR_MED"
pos_input = "name:pos_dealer"
btn_sim_search = "name:STOR_MED_SEARCH_BUTTON"
link_implicit_fup = "link:Implicit Assigned FUP"
link_implicit_quota = "link:Implicit Data Quota"
link_implicit_bc_number = "link:BC Number"
link_preferred_num = "link:Preferred Number"
link_national_num1 = "link:National Number 1"
link_national_num2 = "link:National Number 2"
link_national_num3 = "link:National Number 3"
national_num = "name:JSP_FIELD"
btn_msisdn_search = "name:DIRNUM_ASSIGN_SEARCH_BUTTON"
sim_input = "name:STMEDNO"
btn_input_search = "name:SuSubmitButton"
msisdn_input = "name:NUMBER"
btn_msisdn_input_inner = "name:CO_ORIGINAL_DIRNUM"
main_dir_num = "name:MAIN_DIR_NUM"
btn_set_dir_num = "name:MAIN_DIR_NUM_BUTTON"
chkbox_accnt_owner = "name:Copy_Acc_Details"

# App_Page : Search
resource_type = "name:RESOURCE"
resource_num = "name:RESOURCENO"
cust_num = "name:CS_CODE"
contract_code = "name:CO_ID_PUB"
btn_search = "name:SuSubmitButton"
table_search = "class:DATable"
btn_accnt_search = "name:SearchButtonPressed"
btn_cons_accnt_search = "name:Search_Button"

# App_Page : Enterprise contacts information
nationality = "name:ADR_NATIONALITY"
ent_id_type = "name:IDTYPE_CODE"
establish_expiry = "name:EstablishmentCardExpiryDate_Key"
establish_number = "name:EXT_ESTB_CARD_NUMBER"
id_doc_number = "name:ADR_IDNO"
ent_org = "name:ADR_NAME"
ent_firstname = "name:ADR_FNAME"
ent_lastname = "name:ADR_LNAME"
ent_contactno = "name:ARCN1_FLAG"
ent_alt_num = "name:ADR_PHN1"
emailid = "name:CA_Email"
pincode = "name:ADR_COUNTY"
city = "name:ADR_CITY"
state = "name:ADR_STATE"
segment = "name:PRG_CODE"
subscriber_segment = "name:newprgcode"
billcycle = "name:CS_BILLCYCLE"
btn_next = "name:SuNextStepButton"
sales_channel = "name:SALES_CHANNEL_COMBOBOX"
ent_CNAP = "name:CNAP"
ent_dob = "name:ADR_BIRTHDT"

# App_Page : Enterprise account level and subscriber selection
type_position = "name:Create"
type_position_filter = "name:filterButton"
btn_newcust = "name:NewCustomer_Button"
chkbox_payment_resp = "name:PAYMENT_RESP"
tree_plus_imag = "xpath://a/img[contains(@src,'treetable_plusbottom')]"
plus_create_large_account = "xpath://a[contains(text(),'Create large account')]/../preceding-sibling::td/a/img[contains(@src,'plus')]"
radio_tree_grp = "name:TCB_Tree_Result"

# App_Page : Enterprise VPN
btn_create_contract = "name:Add_Button"
link_VPN_owner_contract = "link:VPN owner contract"
btn_rateplan_filter = "name:SetProduct_Button"
service_pkg = "name:SERVICE_PACKAGE"
btn_servicepkg_filter = "name:SetServicePackage_Button"
link_vpn_admin = "link:IN VPN admin"
link_vpn_rating = "link:VPN Rating"
vpn_rating = "name:SELECTED"

btn_assign = "name:AddServiceResource_Button"
vpn_name = "name:VPN_NAME"
btn_vpn_search = "name:REQ_SEARCH_BUTTON"
vpn_public_number = "name:NUMBER"
vpn_status = "name:STATUS"
btn_status_filter = "name:SetContractStatusButton"
reason = "name:REASON"
btn_finish = "name:Finish_Button"
contractcode_msg = "xpath://span[@class='DAHeaderTxt'][contains(text(),'Contract code')]"

# App_Page : mapped keyword- Enter consumer account information
account_template = "name:CustomerType_ComboBox"
btn_account_template_filter = "name:CustomerType_Selection_Button"
btn_segment_filter = "name:enableGroupSelection"

# App_Page : mapped keyword- Enter consumer details
cons_title = "name:Contact_Title"
cons_firstname = "name:Contact_FirstName"
cons_lastname = "name:Contact_LastName"
id_type = "name:Contact_DocumentType"
btn_id_type_filter = "name:DrivingLicenseEmirate_FilterButton"
id_number = "name:Contact_DocumentNo"
btn_id_number_validate = "name:Validate_ID_Button"
id_issue_date = "name:ID_Issue_Date"
id_expiry_date = "name:ID_Expiration_Date"
cons_nationality = "name:Contact_Nationality"
btn_nationality_filter = "name:Nationality_FilterButton"
visa_type = "name:Contact_VisaType"
visa_number = "name:ADR_PHN2"
visa_expiry_date = "name:Visa_Expiration_Date_Key"
cons_birth_date = "name:ContactBirthDate"
cons_alt_num = "name:ADR_PHN1"
cons_email = "name:Contact_EmailAddr"
monthly_income = "name:ADR_TAXNO"
cons_gender = "name:contactFormGender"
bill_lang = "name:LNG_CODE"
promo_msg = "name:DirectMarketingEITC"
revenue_segment = "name:revSegment"

# App_Page : mapped keyword- Enter Billing address
tower = "name:ADR_NOTE1"
street = "ADR_STREET"
unit_num = "ADR_STREETNO"
pobox = "name:ADR_ZIP"
pref_bill_delivery = "name:BA_BillMethod"
custcode_msg = "xpath://span[@class='DAHeaderTxt'][contains(text(),'Customer code')]"


link_bcp = "link:Business Calling Circle fee"
link_vpn_number = "link:VPN Number"
link_plan_flavour = "link:Plan Flavour"
link_flavour = "link:Flavour"
flavour_list = "name:SELECTED"
sales_agentcode = "name:sales_agent_code"
bmp_commitment_val = "name:BMP_COMBO_NAME"
activity_number = "name:ACTIVITY_NUMBER"

# chnage contract status flow [Change contract status|Deactivated|Disconnection requested by Customer]
link_change_contract_status = "link:Change contract status"
drop_new_status = "name:CO_STATUS"
btn_new_status_filter = "name:ShowCorrectReasons_Button"
contract_reason = "name:REASON"
action_type = "name:ACTION_DES"
btn_exec_immediate = "name:name:JSP_EXECUTE_IMMEDIATE_BUTTON"
